[package]
name = "mentical"
version = "0.1.0"
authors = ["importly <aryankuthakur@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
